image:
  repository: ghcr.io/conanctl/university-project-kuberule/agent
  tag: latest
  pullPolicy: Always

backend:
  endpoint: http://backend:18081

cluster:
  id: ""

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

serviceAccount:
  create: true
  name: kuberule-agent
