import { Finding, GuardrailPack } from "./types"

export const mockGuardrails: GuardrailPack[] = [
  {
    id: 1,
    name: "kube-security",
    version: "1.0.0",
    loaded_at: "2026-02-01T10:00:00Z",
    pack: {
      metadata: {
        name: "kube-security",
        version: "1.0.0",
      },
      spec: {
        description: "Kubernetes security best practices and hardening guardrails",
        owner: "security-team",
        guardrails: [
          {
            id: "gr-001",
            title: "Pod Security Policy Enforcement",
            category: "Security",
            severity: "critical",
            target: "Pod",
            check: {
              type: "pod_security_policy",
              params: {
                allowPrivileged: false,
                runAsNonRoot: true,
              },
            },
            remediationHint: "Apply security context with restrictive policies",
            rationale: "Prevents privilege escalation and unauthorized container access",
          },
          {
            id: "gr-002",
            title: "Resource Limits and Requests",
            category: "Resource Management",
            severity: "high",
            target: "Deployment",
            check: {
              type: "resource_limits",
              params: {
                requireLimits: true,
                requireRequests: true,
              },
            },
            remediationHint: "Define CPU and memory limits for all containers",
            rationale: "Ensures fair resource allocation and prevents resource starvation",
          },
          {
            id: "gr-003",
            title: "Image Scanning and Vulnerability Check",
            category: "Image Security",
            severity: "high",
            target: "Pod",
            check: {
              type: "image_scan",
              params: {
                registry: "trusted",
                maxSeverity: "medium",
              },
            },
            remediationHint: "Use only scanned images from trusted registries",
            rationale: "Prevents deployment of vulnerable container images",
          },
          {
            id: "gr-004",
            title: "Network Policy Enforcement",
            category: "Network Security",
            severity: "high",
            target: "Namespace",
            check: {
              type: "network_policy",
              params: {
                required: true,
              },
            },
            remediationHint: "Implement ingress and egress network policies",
            rationale: "Controls traffic flow and prevents lateral movement",
          },
        ],
      },
    },
  },
  {
    id: 2,
    name: "compliance-standards",
    version: "2.1.0",
    loaded_at: "2026-02-01T10:15:00Z",
    pack: {
      metadata: {
        name: "compliance-standards",
        version: "2.1.0",
      },
      spec: {
        description: "Compliance and regulatory requirements guardrails",
        owner: "compliance-team",
        guardrails: [
          {
            id: "gr-005",
            title: "RBAC Configuration Validation",
            category: "Compliance",
            severity: "high",
            target: "ClusterRole",
            check: {
              type: "rbac_validation",
              params: {
                allowWildcards: false,
              },
            },
            remediationHint: "Use principle of least privilege for RBAC roles",
            rationale: "Enforces least privilege access control",
          },
          {
            id: "gr-006",
            title: "Audit Logging Configuration",
            category: "Compliance",
            severity: "medium",
            target: "Cluster",
            check: {
              type: "audit_logging",
              params: {
                enabled: true,
              },
            },
            remediationHint: "Enable and configure audit logging for the cluster",
            rationale: "Provides audit trail for compliance and security investigations",
          },
          {
            id: "gr-007",
            title: "Data Encryption at Rest",
            category: "Compliance",
            severity: "high",
            target: "PersistentVolume",
            check: {
              type: "encryption_at_rest",
              params: {
                required: true,
              },
            },
            remediationHint: "Enable encryption for storage backends",
            rationale: "Protects sensitive data from unauthorized access",
          },
        ],
      },
    },
  },
  {
    id: 3,
    name: "operational-hygiene",
    version: "1.5.2",
    loaded_at: "2026-02-01T10:30:00Z",
    pack: {
      metadata: {
        name: "operational-hygiene",
        version: "1.5.2",
      },
      spec: {
        description: "Operational best practices and cluster hygiene",
        owner: "infrastructure-team",
        guardrails: [
          {
            id: "gr-008",
            title: "Container Image Registry Validation",
            category: "Hygiene",
            severity: "medium",
            target: "Pod",
            check: {
              type: "registry_validation",
              params: {
                allowedRegistries: ["registry.company.com", "ghcr.io"],
              },
            },
            remediationHint: "Use only approved container image registries",
            rationale: "Ensures image provenance and reduces supply chain risk",
          },
          {
            id: "gr-009",
            title: "Label and Annotation Standards",
            category: "Hygiene",
            severity: "low",
            target: "Pod",
            check: {
              type: "label_validation",
              params: {
                requiredLabels: ["app", "version", "owner"],
              },
            },
            remediationHint: "Add required labels to all Kubernetes objects",
            rationale: "Enables proper resource tracking and management",
          },
          {
            id: "gr-010",
            title: "Pod Disruption Budget Configuration",
            category: "Hygiene",
            severity: "medium",
            target: "Deployment",
            check: {
              type: "pdb_check",
              params: {
                required: true,
              },
            },
            remediationHint: "Define Pod Disruption Budgets for high availability",
            rationale: "Ensures application availability during maintenance",
          },
          {
            id: "gr-011",
            title: "Health Check Configuration",
            category: "Hygiene",
            severity: "medium",
            target: "Pod",
            check: {
              type: "health_checks",
              params: {
                requireLiveness: true,
                requireReadiness: true,
              },
            },
            remediationHint: "Configure liveness and readiness probes",
            rationale: "Enables automatic container recovery and traffic management",
          },
        ],
      },
    },
  },
]

export const mockFindings: Finding[] = [
  {
    id: 1,
    guardrail_id: "gr-001",
    title: "Pod Security Policy Violation",
    category: "Security",
    severity: "critical",
    target_type: "Pod",
    target_identifier: "default/nginx-pod-1",
    cluster_id: "cluster-1",
    namespace: "default",
    status: "open",
    first_seen_at: "2026-01-28T10:00:00Z",
    last_seen_at: "2026-02-01T15:30:00Z",
    evidence: { issue: "Pod running with root privileges" },
    remediation_hint: "Add security context with runAsNonRoot: true",
    owner_label_value: "platform-team",
  },
  {
    id: 2,
    guardrail_id: "gr-002",
    title: "Missing Resource Limits",
    category: "Resource Management",
    severity: "high",
    target_type: "Deployment",
    target_identifier: "kube-system/coredns",
    cluster_id: "cluster-1",
    namespace: "kube-system",
    status: "open",
    first_seen_at: "2026-01-29T08:15:00Z",
    last_seen_at: "2026-02-01T14:20:00Z",
    evidence: { missing: ["limits", "requests"] },
    remediation_hint: "Define resource limits and requests in deployment spec",
    owner_label_value: "infrastructure-team",
  },
  {
    id: 3,
    guardrail_id: "gr-003",
    title: "Outdated Base Image",
    category: "Image Security",
    severity: "high",
    target_type: "Pod",
    target_identifier: "production/app-server-1",
    cluster_id: "cluster-2",
    namespace: "production",
    status: "open",
    first_seen_at: "2026-01-25T12:00:00Z",
    last_seen_at: "2026-02-01T16:00:00Z",
    evidence: { image: "ubuntu:18.04", recommended: "ubuntu:22.04" },
    remediation_hint: "Update to latest LTS base image",
    owner_label_value: "app-team",
  },
  {
    id: 4,
    guardrail_id: "gr-004",
    title: "Exposed Service Port",
    category: "Network Security",
    severity: "medium",
    target_type: "Service",
    target_identifier: "default/database-service",
    cluster_id: "cluster-1",
    namespace: "default",
    status: "open",
    first_seen_at: "2026-01-30T09:30:00Z",
    last_seen_at: "2026-02-01T13:45:00Z",
    evidence: { port: 5432, exposed: true },
    remediation_hint: "Use ClusterIP service type instead of LoadBalancer",
    owner_label_value: "database-team",
  },
  {
    id: 5,
    guardrail_id: "gr-005",
    title: "Missing Network Policy",
    category: "Network Security",
    severity: "medium",
    target_type: "Namespace",
    target_identifier: "staging",
    cluster_id: "cluster-2",
    namespace: "staging",
    status: "open",
    first_seen_at: "2026-01-31T11:00:00Z",
    last_seen_at: "2026-02-01T15:00:00Z",
    evidence: { policies: 0 },
    remediation_hint: "Implement network policies for ingress/egress control",
    owner_label_value: "security-team",
  },
  {
    id: 6,
    guardrail_id: "gr-006",
    title: "Unsafe Volume Mount",
    category: "Security",
    severity: "low",
    target_type: "Pod",
    target_identifier: "kube-system/metrics-server",
    cluster_id: "cluster-1",
    namespace: "kube-system",
    status: "open",
    first_seen_at: "2026-02-01T08:00:00Z",
    last_seen_at: "2026-02-01T16:30:00Z",
    evidence: { path: "/host/sys", readOnly: false },
    remediation_hint: "Mount as read-only or use projected volumes",
    owner_label_value: "platform-team",
  },
]
