import { Finding } from "./types"

export const mockFindings: Finding[] = [
  {
    id: 1,
    guardrail_id: "gr-001",
    title: "Pod Security Policy Violation",
    category: "Security",
    severity: "critical",
    target_type: "Pod",
    target_identifier: "default/nginx-pod-1",
    cluster_id: "cluster-1",
    namespace: "default",
    status: "open",
    first_seen_at: "2026-01-28T10:00:00Z",
    last_seen_at: "2026-02-01T15:30:00Z",
    evidence: { issue: "Pod running with root privileges" },
    remediation_hint: "Add security context with runAsNonRoot: true",
    owner_label_value: "platform-team",
  },
  {
    id: 2,
    guardrail_id: "gr-002",
    title: "Missing Resource Limits",
    category: "Resource Management",
    severity: "high",
    target_type: "Deployment",
    target_identifier: "kube-system/coredns",
    cluster_id: "cluster-1",
    namespace: "kube-system",
    status: "open",
    first_seen_at: "2026-01-29T08:15:00Z",
    last_seen_at: "2026-02-01T14:20:00Z",
    evidence: { missing: ["limits", "requests"] },
    remediation_hint: "Define resource limits and requests in deployment spec",
    owner_label_value: "infrastructure-team",
  },
  {
    id: 3,
    guardrail_id: "gr-003",
    title: "Outdated Base Image",
    category: "Image Security",
    severity: "high",
    target_type: "Pod",
    target_identifier: "production/app-server-1",
    cluster_id: "cluster-2",
    namespace: "production",
    status: "open",
    first_seen_at: "2026-01-25T12:00:00Z",
    last_seen_at: "2026-02-01T16:00:00Z",
    evidence: { image: "ubuntu:18.04", recommended: "ubuntu:22.04" },
    remediation_hint: "Update to latest LTS base image",
    owner_label_value: "app-team",
  },
  {
    id: 4,
    guardrail_id: "gr-004",
    title: "Exposed Service Port",
    category: "Network Security",
    severity: "medium",
    target_type: "Service",
    target_identifier: "default/database-service",
    cluster_id: "cluster-1",
    namespace: "default",
    status: "open",
    first_seen_at: "2026-01-30T09:30:00Z",
    last_seen_at: "2026-02-01T13:45:00Z",
    evidence: { port: 5432, exposed: true },
    remediation_hint: "Use ClusterIP service type instead of LoadBalancer",
    owner_label_value: "database-team",
  },
  {
    id: 5,
    guardrail_id: "gr-005",
    title: "Missing Network Policy",
    category: "Network Security",
    severity: "medium",
    target_type: "Namespace",
    target_identifier: "staging",
    cluster_id: "cluster-2",
    namespace: "staging",
    status: "open",
    first_seen_at: "2026-01-31T11:00:00Z",
    last_seen_at: "2026-02-01T15:00:00Z",
    evidence: { policies: 0 },
    remediation_hint: "Implement network policies for ingress/egress control",
    owner_label_value: "security-team",
  },
  {
    id: 6,
    guardrail_id: "gr-006",
    title: "Unsafe Volume Mount",
    category: "Security",
    severity: "low",
    target_type: "Pod",
    target_identifier: "kube-system/metrics-server",
    cluster_id: "cluster-1",
    namespace: "kube-system",
    status: "open",
    first_seen_at: "2026-02-01T08:00:00Z",
    last_seen_at: "2026-02-01T16:30:00Z",
    evidence: { path: "/host/sys", readOnly: false },
    remediation_hint: "Mount as read-only or use projected volumes",
    owner_label_value: "platform-team",
  },
]
